# Generated by Django 3.2.21 on 2023-10-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='https://res.cloudinary.com/dqh6bfpwq/image/upload/v1696170756/default_profile_ix4poc.jpg', upload_to='images/'),
        ),
    ]
