# Generated by Django 3.2.21 on 2023-10-16 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='https://res.cloudinary.com/dfezyx4ne/image/upload/v1696338694/media/images/default_profile_pcfhix.jpg', upload_to='images/'),
        ),
    ]
