# Generated by Django 3.2.21 on 2023-12-17 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoitems', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='priority',
        ),
    ]
