# Generated by Django 3.2.21 on 2023-12-17 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todoitems', '0002_remove_todoitem_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoItemPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('priority', models.IntegerField(choices=[('low', 'LOW'), ('medium', 'MEDIUM'), ('high', 'HIGH')])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('todoitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoitems.todoitem')),
            ],
            options={
                'ordering': ['priority', 'created_at'],
            },
        ),
    ]
