# Generated by Django 3.2.21 on 2023-10-05 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolists', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='user',
            new_name='owner',
        ),
    ]
